export enum EnvKeysEnum {
  AppPort = 'APP_PORT',
  NodeEnv = 'NODE_ENV',
  MySecretForSuper = 'MY_SECRET_FOR_SUPER',
  FirebaseApiKey = 'FIREBASE_API_KEY',
  DbHost = 'DB_HOST',
  DbPort = 'DB_PORT',
  DbUser = 'DB_USER',
  DbPass = 'DB_PASS',
  DbName = 'DB_NAME',
  SendGridApiKey = 'SEND_GRID_API_KEY',
  SenderEmail = 'SENDER_EMAIL',
  AsposeBaseUrl = 'ASPOSE_BASE_URL',
  AsposeClientId = 'ASPOSE_CLIENT_ID',
  AsposeClientSecret = 'ASPOSE_CLIENT_SECRET',
  KeanFrontendUrl = 'KEAN_FRONTEND_URL',
  RedisHost = 'REDIS_HOST',
  RedisPort = 'REDIS_PORT',
  RedisUsername = 'REDIS_USERNAME',
  RedisPassword = 'REDIS_PASSWORD',
  AwsRegion = 'aws.region',
  AwsAccessKeyId = 'aws.accessKeyId',
  AwsAccessKeySecret = 'aws.secretAccessKey',
  AwsS3BucketName = 'aws.s3.bucketName',
}
