export enum EnvKeysEnum {
  AppPort = 'APP_PORT',
  NodeEnv = 'NODE_ENV',
  MySecretForSuper = 'MY_SECRET_FOR_SUPER',
  DbHost = 'DB_HOST',
  DbPort = 'DB_PORT',
  DbUser = 'DB_USER',
  DbPass = 'DB_PASS',
  DbName = 'DB_NAME',
  SendGridApiKey = 'SEND_GRID_API_KEY',
  SenderEmail = 'SENDER_EMAIL',
  FrontendUrl = 'FRONTEND_URL',
  AwsRegion = 'aws.region',
  AwsAccessKeyId = 'aws.accessKeyId',
  AwsAccessKeySecret = 'aws.secretAccessKey',
  AwsS3BucketName = 'aws.s3.bucketName',
  // API Documentation
  ApiTitle = 'API_TITLE',
  ApiDescription = 'API_DESCRIPTION',
  ApiVersion = 'API_VERSION',
  ApiContactName = 'API_CONTACT_NAME',
  ApiContactEmail = 'API_CONTACT_EMAIL',
  ApiContactUrl = 'API_CONTACT_URL',
  StagingUrl = 'STAGING_URL',
  ProductionUrl = 'PRODUCTION_URL',
}
