export enum ResourcesEnum {
  Users = 'Users',
  UserRoles = 'User Roles',
  UsersAuth = 'Users Auth',
  Academies = 'Academies',
  AcademyAdmins = 'Academy Admins',
  AtRiskStudents = 'At Risk Students',
  ChallengedQuestions = 'Challenged Questions',
  Courses = 'Courses',
  StudentCourses = 'Student Courses',
  UniversityCourses = 'University Courses',
  Dashboard = 'Dashboard',
  QuestionsBank = 'Questions Bank',
  Scoring = 'Scoring',
  StudentTestSubmissions = 'Student Test Submissions',
  Students = 'Students',
  TestEnrollments = 'Test Enrollments',
  Tests = 'Tests',
  GeneratedTests = 'Generated Tests',
  TestRequests = 'Test Requests',
  StudentTests = 'Student Tests',
  TestSpecifications = 'Test Specifications',
  Announcements = 'Announcements',
  StudentOnboarding = 'Student Onboarding',
  CourseCategories = 'Course Categories',
  Attendance = 'Attendance',
}
